In [2]:
import pandas as pd

## Part 1 exercise
1. Load the wine dataset
1. How many rows are there?
1. What columns are there?
1. What are the minimum and maximum values of the `total_sulfur_dioxide` column?
1. What is the mean of the `pH` column?
1. Which columns are non-numerical?
1. How many missing values do you see?

#### &#x1F4A1; Tip &#x1F4A1;
* Does `read_csv()` read the columns correctly?
* Employ the appropriate parameter (what value should be sent?)

In [ ]:
wine = pd.read_csv("wine_dataset.txt", sep=";")

In [ ]:
wine.shape

(6497, 13)

In [ ]:
wine.columns

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'style'],
      dtype='object')

In [ ]:
wine

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [ ]:
wine.head(10)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,red
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5,red
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7,red
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7,red
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5,red

In [ ]:
wine.describe()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000
mean,7.215307,0.339666,0.318633,5.443235,0.056034,30.525319,115.744574,0.994697,3.218501,0.531268,10.491801,5.818378
std,1.296434,0.164636,0.145318,4.757804,0.035034,17.749400,56.521855,0.002999,0.160787,0.148806,1.192712,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

In [ ]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed_acidity         6497 non-null   float64
 1   volatile_acidity      6497 non-null   float64
 2   citric_acid           6497 non-null   float64
 3   residual_sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free_sulfur_dioxide   6497 non-null   float64
 6   total_sulfur_dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
 12  style                 6497 non-null   object
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB

In [ ]:
wine.dtypes

fixed_acidity           float64
volatile_acidity        float64
citric_acid             float64
residual_sugar          float64
chlorides               float64
free_sulfur_dioxide     float64
total_sulfur_dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
style                    object
dtype: object

In [ ]:
wine.isna().sum()

fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
style                   0
dtype: int64

1. pH < 3.3 and sulfates > 0.6
    1. Extract wines with pH below 3.3 and sulfates above 0.6 using `query`
    1. Repeat, this time with boolean indexing
    1. **Challenge** use boolean indexing to achieve this but **without** and, or etc.

## Part 2 exrecise
1. pH < 3.3 and sulfates > 0.6
    1. Extract wines with pH below 3.3 and sulfates above 0.6 using `query`
    1. Repeat, this time with boolean indexing
    1. **Challenge** use boolean indexing to achieve thes same result, but **without using** "and", "or" etc.

In [5]:
df = pd.read_csv('wine_dataset.txt', sep=';')

In [ ]:
# Q 1A

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.800000,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.800000,5,red
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.100000,5,red
14,8.9,0.62,0.18,3.8,0.176,52.0,145.0,0.99860,3.16,0.88,9.200000,5,red
15,8.9,0.62,0.19,3.9,0.170,51.0,148.0,0.99860,3.17,0.93,9.200000,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,6.0,0.27,0.40,1.7,0.021,18.0,82.0,0.98910,3.24,0.95,13.133333,6,white
6418,5.7,0.40,0.35,5.1,0.026,17.0,113.0,0.99052,3.18,0.67,12.400000,6,white
6426,6.7,0.22,0.33,1.2,0.036,36.0,86.0,0.99058,3.10,0.76,11.400000,6,white
6485,6.2,0.21,0.28,5.7,0.028,45.0,121.0,0.99168,3.21,1.08,12.150000,7,white
6486,6.2,0.41,0.22,1.9,0.023,5.0,56.0,0.98928,3.04,0.79,13.000000,7,white

In [12]:
print(df.columns)

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'style'],
      dtype='object')

In [14]:
# answer:
df[(df['pH'] < 3.3) & (df['sulphates'] > 0.6)]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.800000,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.800000,5,red
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.100000,5,red
14,8.9,0.62,0.18,3.8,0.176,52.0,145.0,0.99860,3.16,0.88,9.200000,5,red
15,8.9,0.62,0.19,3.9,0.170,51.0,148.0,0.99860,3.17,0.93,9.200000,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,6.0,0.27,0.40,1.7,0.021,18.0,82.0,0.98910,3.24,0.95,13.133333,6,white
6418,5.7,0.40,0.35,5.1,0.026,17.0,113.0,0.99052,3.18,0.67,12.400000,6,white
6426,6.7,0.22,0.33,1.2,0.036,36.0,86.0,0.99058,3.10,0.76,11.400000,6,white
6485,6.2,0.21,0.28,5.7,0.028,45.0,121.0,0.99168,3.21,1.08,12.150000,7,white
6486,6.2,0.41,0.22,1.9,0.023,5.0,56.0,0.98928,3.04,0.79,13.000000,7,white

In [ ]:
# Q 1B

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.800000,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.800000,5,red
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.100000,5,red
14,8.9,0.62,0.18,3.8,0.176,52.0,145.0,0.99860,3.16,0.88,9.200000,5,red
15,8.9,0.62,0.19,3.9,0.170,51.0,148.0,0.99860,3.17,0.93,9.200000,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,6.0,0.27,0.40,1.7,0.021,18.0,82.0,0.98910,3.24,0.95,13.133333,6,white
6418,5.7,0.40,0.35,5.1,0.026,17.0,113.0,0.99052,3.18,0.67,12.400000,6,white
6426,6.7,0.22,0.33,1.2,0.036,36.0,86.0,0.99058,3.10,0.76,11.400000,6,white
6485,6.2,0.21,0.28,5.7,0.028,45.0,121.0,0.99168,3.21,1.08,12.150000,7,white
6486,6.2,0.41,0.22,1.9,0.023,5.0,56.0,0.98928,3.04,0.79,13.000000,7,white

In [18]:
df.query("pH < 3.3 and sulphates > 0.6")

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.800000,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.800000,5,red
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.100000,5,red
14,8.9,0.62,0.18,3.8,0.176,52.0,145.0,0.99860,3.16,0.88,9.200000,5,red
15,8.9,0.62,0.19,3.9,0.170,51.0,148.0,0.99860,3.17,0.93,9.200000,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,6.0,0.27,0.40,1.7,0.021,18.0,82.0,0.98910,3.24,0.95,13.133333,6,white
6418,5.7,0.40,0.35,5.1,0.026,17.0,113.0,0.99052,3.18,0.67,12.400000,6,white
6426,6.7,0.22,0.33,1.2,0.036,36.0,86.0,0.99058,3.10,0.76,11.400000,6,white
6485,6.2,0.21,0.28,5.7,0.028,45.0,121.0,0.99168,3.21,1.08,12.150000,7,white
6486,6.2,0.41,0.22,1.9,0.023,5.0,56.0,0.98928,3.04,0.79,13.000000,7,white

In [ ]:
# Q 1C

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.800000,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.800000,5,red
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.100000,5,red
14,8.9,0.62,0.18,3.8,0.176,52.0,145.0,0.99860,3.16,0.88,9.200000,5,red
15,8.9,0.62,0.19,3.9,0.170,51.0,148.0,0.99860,3.17,0.93,9.200000,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,6.0,0.27,0.40,1.7,0.021,18.0,82.0,0.98910,3.24,0.95,13.133333,6,white
6418,5.7,0.40,0.35,5.1,0.026,17.0,113.0,0.99052,3.18,0.67,12.400000,6,white
6426,6.7,0.22,0.33,1.2,0.036,36.0,86.0,0.99058,3.10,0.76,11.400000,6,white
6485,6.2,0.21,0.28,5.7,0.028,45.0,121.0,0.99168,3.21,1.08,12.150000,7,white
6486,6.2,0.41,0.22,1.9,0.023,5.0,56.0,0.98928,3.04,0.79,13.000000,7,white

2. Wines by quality level
    1. How many wines are there *of each quality level* with chlorides <= 0.03?
    1. How many wines are there *of each quality level* with chlorides >= 0.07?
    1. Is there anything to learn from the comparison about the relation between chlorides and quality?

**Tip 1**: use `.sort_index()` to see the count by order of values.

**Tip 2** (for C): add `normalize=True` as an argument to `value_counts`

In [ ]:
# Q 2A

3      2
4      9
5     72
6    241
7    192
8     48
9      2
Name: quality, dtype: int64

In [ ]:
# Q 2B

3     11
4     48
5    692
6    553
7    119
8     13
Name: quality, dtype: int64

In [ ]:
# Q 2C

3     0.353357
4     1.590106
5    12.720848
6    42.579505
7    33.922261
8     8.480565
9     0.353357
Name: quality, dtype: float64

In [ ]:
# Q 2C

3     0.766017
4     3.342618
5    48.189415
6    38.509749
7     8.286908
8     0.905292
Name: quality, dtype: float64

3. Extract all rows where `free_sulfur_dioxide` is between 98 and 108 using logical indexing:
    1. Using `&` (and)
    1. **Challenge** using `Series.between(a, b)` (Refer to the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.between.html)  if needed )
   
1. A dataframe for white wine
    1. create a dataframe called `white` that has just wines of type "white".
    1. **Challenge:** explain why the expression `wine.style=='white'` does not produce the expected result.
1. Using the dataframe `white`, extract all rows where quality is either 3 or 9
    1. Using logical indexing with `|` (or)
    1. **Challenge:** using `.isin` ([doc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html))
1. Sort the previous result by quality

In [ ]:
# Q 3A

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
5060,6.7,0.24,0.30,3.85,0.042,105.0,179.0,0.99189,3.04,0.59,11.3,8,white
5069,6.7,0.24,0.30,3.85,0.042,105.0,179.0,0.99189,3.04,0.59,11.3,8,white
5119,6.0,0.23,0.15,9.70,0.048,101.0,207.0,0.99571,3.05,0.30,9.1,5,white
5122,6.0,0.23,0.15,9.70,0.048,101.0,207.0,0.99571,3.05,0.30,9.1,5,white
5219,6.3,0.20,0.26,4.70,0.040,108.0,168.0,0.99278,3.07,0.75,10.7,7,white
5460,6.2,0.22,0.30,12.40,0.054,108.0,152.0,0.99728,3.10,0.47,9.5,6,white
5461,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white
5462,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white
5468,6.2,0.22,0.30,12.40,0.054,108.0,152.0,0.99728,3.10,0.47,9.5,6,white
5470,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white

In [19]:
df[(df['free_sulfur_dioxide'] > 97) & (df['free_sulfur_dioxide'] < 109)]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
5060,6.7,0.24,0.30,3.85,0.042,105.0,179.0,0.99189,3.04,0.59,11.3,8,white
5069,6.7,0.24,0.30,3.85,0.042,105.0,179.0,0.99189,3.04,0.59,11.3,8,white
5119,6.0,0.23,0.15,9.70,0.048,101.0,207.0,0.99571,3.05,0.30,9.1,5,white
5122,6.0,0.23,0.15,9.70,0.048,101.0,207.0,0.99571,3.05,0.30,9.1,5,white
5219,6.3,0.20,0.26,4.70,0.040,108.0,168.0,0.99278,3.07,0.75,10.7,7,white
5460,6.2,0.22,0.30,12.40,0.054,108.0,152.0,0.99728,3.10,0.47,9.5,6,white
5461,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white
5462,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white
5468,6.2,0.22,0.30,12.40,0.054,108.0,152.0,0.99728,3.10,0.47,9.5,6,white
5470,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white

In [24]:
df[df['free_sulfur_dioxide'].between(98, 108)]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
5060,6.7,0.24,0.30,3.85,0.042,105.0,179.0,0.99189,3.04,0.59,11.3,8,white
5069,6.7,0.24,0.30,3.85,0.042,105.0,179.0,0.99189,3.04,0.59,11.3,8,white
5119,6.0,0.23,0.15,9.70,0.048,101.0,207.0,0.99571,3.05,0.30,9.1,5,white
5122,6.0,0.23,0.15,9.70,0.048,101.0,207.0,0.99571,3.05,0.30,9.1,5,white
5219,6.3,0.20,0.26,4.70,0.040,108.0,168.0,0.99278,3.07,0.75,10.7,7,white
5460,6.2,0.22,0.30,12.40,0.054,108.0,152.0,0.99728,3.10,0.47,9.5,6,white
5461,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white
5462,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white
5468,6.2,0.22,0.30,12.40,0.054,108.0,152.0,0.99728,3.10,0.47,9.5,6,white
5470,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white

In [ ]:
# Q 3B

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
5060,6.7,0.24,0.30,3.85,0.042,105.0,179.0,0.99189,3.04,0.59,11.3,8,white
5069,6.7,0.24,0.30,3.85,0.042,105.0,179.0,0.99189,3.04,0.59,11.3,8,white
5119,6.0,0.23,0.15,9.70,0.048,101.0,207.0,0.99571,3.05,0.30,9.1,5,white
5122,6.0,0.23,0.15,9.70,0.048,101.0,207.0,0.99571,3.05,0.30,9.1,5,white
5219,6.3,0.20,0.26,4.70,0.040,108.0,168.0,0.99278,3.07,0.75,10.7,7,white
5460,6.2,0.22,0.30,12.40,0.054,108.0,152.0,0.99728,3.10,0.47,9.5,6,white
5461,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white
5462,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white
5468,6.2,0.22,0.30,12.40,0.054,108.0,152.0,0.99728,3.10,0.47,9.5,6,white
5470,6.5,0.27,0.19,6.60,0.045,98.0,175.0,0.99364,3.16,0.34,10.1,6,white

In [37]:
# Q 4
white = df[df['style'] == 'white']

In [27]:
white

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1599,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,white
1600,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,white
1601,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,white
1602,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,white
1603,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [38]:
df.style == 'white'

False

In [35]:
white = df[df['style'] != 'white']
white

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,red
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,red
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,red
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,red
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,red

In [ ]:
# Q 5A

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1850,8.5,0.260,0.21,16.20,0.074,41.0,197.0,0.99800,3.02,0.50,9.8,3,white
1852,5.8,0.240,0.44,3.50,0.029,5.0,109.0,0.99130,3.53,0.43,11.7,3,white
1893,9.1,0.590,0.38,1.60,0.066,34.0,182.0,0.99680,3.23,0.38,8.5,3,white
2044,7.1,0.320,0.32,11.00,0.038,16.0,66.0,0.99370,3.24,0.40,11.5,3,white
2339,6.9,0.390,0.40,4.60,0.022,5.0,19.0,0.99150,3.31,0.37,12.6,3,white
2373,9.1,0.270,0.45,10.60,0.035,28.0,124.0,0.99700,3.20,0.46,10.4,9,white
2419,6.6,0.360,0.29,1.60,0.021,24.0,85.0,0.98965,3.41,0.61,12.4,9,white
2426,7.4,0.240,0.36,2.00,0.031,27.0,139.0,0.99055,3.28,0.48,12.5,9,white
2472,10.3,0.170,0.47,1.40,0.037,5.0,33.0,0.99390,2.89,0.28,9.6,3,white
2475,6.9,0.360,0.34,4.20,0.018,57.0,119.0,0.98980,3.28,0.36,12.7,9,white
2633,7.9,0.640,0.46,10.60,0.244,33.0,227.0,0.99830,2.87,0.74,9.1,3,white
2828,8.3,0.330,0.42,1.15,0.033,18.0,96.0,0.99110,3.20,0.32,12.4,3,white
3016,8.6,0.550,0.35,15.55,0.057,35.5,366.5,1.00010,3.04,0.63,11.0,3,white
3083,7.5,0.320,0.24,4.60,0.053,8.0,134.0,0.99580,3.14,0.50,9.1,3,white
3204,7.1,0.260,0.49,2.20,0.032,31.0,113.0,0.99030,3.37,0.42,12.9,9,white
3287,6.7,0.250,0.26,1.55,0.041,118.5,216.0,0.99490,3.55,0.63,9.4,3,white
3530,7.1,0.490,0.22,2.00,0.047,146.5,307.5,0.99240,3.24,0.37,11.0,3,white
3649,11.8,0.230,0.38,11.10,0.034,15.0,123.0,0.99970,2.93,0.55,9.7,3,white
3972,7.6,0.480,0.37,1.20,0.034,5.0,57.0,0.99256,3.05,0.54,10.4,3,white
4686,6.1,0.200,0.34,9.50,0.041,38.0,201.0,0.99500,3.14,0.44,10.1,3,white
4864,4.2,0.215,0.23,5.10,0.041,64.0,157.0,0.99688,3.42,0.44,8.0,3,white
4906,9.4,0.240,0.29,8.50,0.037,124.0,208.0,0.99395,2.90,0.38,11.0,3,white
5008,6.2,0.230,0.35,0.70,0.051,24.0,111.0,0.99160,3.37,0.43,11.0,3,white
5409,6.8,0.260,0.34,15.10,0.060,42.0,162.0,0.99705,3.24,0.52,10.5,3,white
6344,6.1,0.260,0.25,2.90,0.047,289.0,440.0,0.99314,3.44,0.64,10.5,3,white

In [ ]:
# Q 5B

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1850,8.5,0.260,0.21,16.20,0.074,41.0,197.0,0.99800,3.02,0.50,9.8,3,white
1852,5.8,0.240,0.44,3.50,0.029,5.0,109.0,0.99130,3.53,0.43,11.7,3,white
1893,9.1,0.590,0.38,1.60,0.066,34.0,182.0,0.99680,3.23,0.38,8.5,3,white
2044,7.1,0.320,0.32,11.00,0.038,16.0,66.0,0.99370,3.24,0.40,11.5,3,white
2339,6.9,0.390,0.40,4.60,0.022,5.0,19.0,0.99150,3.31,0.37,12.6,3,white
2373,9.1,0.270,0.45,10.60,0.035,28.0,124.0,0.99700,3.20,0.46,10.4,9,white
2419,6.6,0.360,0.29,1.60,0.021,24.0,85.0,0.98965,3.41,0.61,12.4,9,white
2426,7.4,0.240,0.36,2.00,0.031,27.0,139.0,0.99055,3.28,0.48,12.5,9,white
2472,10.3,0.170,0.47,1.40,0.037,5.0,33.0,0.99390,2.89,0.28,9.6,3,white
2475,6.9,0.360,0.34,4.20,0.018,57.0,119.0,0.98980,3.28,0.36,12.7,9,white
2633,7.9,0.640,0.46,10.60,0.244,33.0,227.0,0.99830,2.87,0.74,9.1,3,white
2828,8.3,0.330,0.42,1.15,0.033,18.0,96.0,0.99110,3.20,0.32,12.4,3,white
3016,8.6,0.550,0.35,15.55,0.057,35.5,366.5,1.00010,3.04,0.63,11.0,3,white
3083,7.5,0.320,0.24,4.60,0.053,8.0,134.0,0.99580,3.14,0.50,9.1,3,white
3204,7.1,0.260,0.49,2.20,0.032,31.0,113.0,0.99030,3.37,0.42,12.9,9,white
3287,6.7,0.250,0.26,1.55,0.041,118.5,216.0,0.99490,3.55,0.63,9.4,3,white
3530,7.1,0.490,0.22,2.00,0.047,146.5,307.5,0.99240,3.24,0.37,11.0,3,white
3649,11.8,0.230,0.38,11.10,0.034,15.0,123.0,0.99970,2.93,0.55,9.7,3,white
3972,7.6,0.480,0.37,1.20,0.034,5.0,57.0,0.99256,3.05,0.54,10.4,3,white
4686,6.1,0.200,0.34,9.50,0.041,38.0,201.0,0.99500,3.14,0.44,10.1,3,white
4864,4.2,0.215,0.23,5.10,0.041,64.0,157.0,0.99688,3.42,0.44,8.0,3,white
4906,9.4,0.240,0.29,8.50,0.037,124.0,208.0,0.99395,2.90,0.38,11.0,3,white
5008,6.2,0.230,0.35,0.70,0.051,24.0,111.0,0.99160,3.37,0.43,11.0,3,white
5409,6.8,0.260,0.34,15.10,0.060,42.0,162.0,0.99705,3.24,0.52,10.5,3,white
6344,6.1,0.260,0.25,2.90,0.047,289.0,440.0,0.99314,3.44,0.64,10.5,3,white

In [ ]:
# 6

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1850,8.5,0.260,0.21,16.20,0.074,41.0,197.0,0.99800,3.02,0.50,9.8,3,white
5008,6.2,0.230,0.35,0.70,0.051,24.0,111.0,0.99160,3.37,0.43,11.0,3,white
4906,9.4,0.240,0.29,8.50,0.037,124.0,208.0,0.99395,2.90,0.38,11.0,3,white
4864,4.2,0.215,0.23,5.10,0.041,64.0,157.0,0.99688,3.42,0.44,8.0,3,white
4686,6.1,0.200,0.34,9.50,0.041,38.0,201.0,0.99500,3.14,0.44,10.1,3,white
3972,7.6,0.480,0.37,1.20,0.034,5.0,57.0,0.99256,3.05,0.54,10.4,3,white
3649,11.8,0.230,0.38,11.10,0.034,15.0,123.0,0.99970,2.93,0.55,9.7,3,white
3530,7.1,0.490,0.22,2.00,0.047,146.5,307.5,0.99240,3.24,0.37,11.0,3,white
3287,6.7,0.250,0.26,1.55,0.041,118.5,216.0,0.99490,3.55,0.63,9.4,3,white
3083,7.5,0.320,0.24,4.60,0.053,8.0,134.0,0.99580,3.14,0.50,9.1,3,white
5409,6.8,0.260,0.34,15.10,0.060,42.0,162.0,0.99705,3.24,0.52,10.5,3,white
3016,8.6,0.550,0.35,15.55,0.057,35.5,366.5,1.00010,3.04,0.63,11.0,3,white
2633,7.9,0.640,0.46,10.60,0.244,33.0,227.0,0.99830,2.87,0.74,9.1,3,white
2472,10.3,0.170,0.47,1.40,0.037,5.0,33.0,0.99390,2.89,0.28,9.6,3,white
2339,6.9,0.390,0.40,4.60,0.022,5.0,19.0,0.99150,3.31,0.37,12.6,3,white
2044,7.1,0.320,0.32,11.00,0.038,16.0,66.0,0.99370,3.24,0.40,11.5,3,white
1893,9.1,0.590,0.38,1.60,0.066,34.0,182.0,0.99680,3.23,0.38,8.5,3,white
1852,5.8,0.240,0.44,3.50,0.029,5.0,109.0,0.99130,3.53,0.43,11.7,3,white
2828,8.3,0.330,0.42,1.15,0.033,18.0,96.0,0.99110,3.20,0.32,12.4,3,white
6344,6.1,0.260,0.25,2.90,0.047,289.0,440.0,0.99314,3.44,0.64,10.5,3,white
2475,6.9,0.360,0.34,4.20,0.018,57.0,119.0,0.98980,3.28,0.36,12.7,9,white
3204,7.1,0.260,0.49,2.20,0.032,31.0,113.0,0.99030,3.37,0.42,12.9,9,white
2426,7.4,0.240,0.36,2.00,0.031,27.0,139.0,0.99055,3.28,0.48,12.5,9,white
2419,6.6,0.360,0.29,1.60,0.021,24.0,85.0,0.98965,3.41,0.61,12.4,9,white
2373,9.1,0.270,0.45,10.60,0.035,28.0,124.0,0.99700,3.20,0.46,10.4,9,white

7. Extract multiple row/ column by index/name:
    1. Retrieve rows 22, 44, 55
    1. For the same rows, retrieve just the wine style and density
    1. **Challenge**: Retrieve just the wine style and density for every 50th rows

**Tip 1**: lists are valid arguments to `loc`

**Tip 2 (for 6c)**: how would you extract every 50th row from a `list`?


8. Sorting
    1. Display the five wines with lowest `residual_sugar`, sorted ascending
    1. Display the five wines with highest `density`, sorted descending
    1. Display the five wines with **highest** `density`, sorted **ascending**
    1. Display just the `alcohol` values for the five wines with highest density

**Tip 3 (for 7b):** Use `.head()` to get the *first* 5 lines of a dataframe

**Tip 4 (for 7c):** Use `.tail()` to get the *last* 5 lines of a dataframe

In [ ]:
# Q 7A

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
22,7.9,0.43,0.21,1.6,0.106,10.0,37.0,0.9966,3.17,0.91,9.5,5,red
44,6.8,0.67,0.02,1.8,0.050,5.0,11.0,0.9962,3.48,0.52,9.5,5,red
55,7.7,0.62,0.04,3.8,0.084,25.0,45.0,0.9978,3.34,0.53,9.5,5,red

In [ ]:
# Q 7B

   style  density
22   red   0.9966
44   red   0.9962
55   red   0.9978

      style  density
0       red  0.99780
50      red  0.99710
100     red  0.99720
150     red  0.99580
200     red  0.99695
...     ...      ...
6250  white  0.98966
6300  white  0.99480
6350  white  0.99472
6400  white  0.99142
6450  white  0.99488

[130 rows x 2 columns]

In [ ]:
# Q 8A

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
3644,8.7,0.24,0.35,0.6,0.042,11.0,71.0,0.9926,3.08,0.38,10.6,5,white
3638,8.7,0.24,0.35,0.6,0.042,11.0,71.0,0.9926,3.08,0.38,10.6,5,white
6281,6.8,0.32,0.33,0.7,0.027,15.0,66.0,0.9899,3.11,0.31,11.8,6,white
5008,6.2,0.23,0.35,0.7,0.051,24.0,111.0,0.9916,3.37,0.43,11.0,3,white
4186,5.1,0.14,0.25,0.7,0.039,15.0,89.0,0.9919,3.22,0.43,9.2,6,white

In [ ]:
# Q 8B

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
4380,7.8,0.965,0.60,65.8,0.074,8.0,160.0,1.03898,3.39,0.69,11.7,6,white
3262,7.9,0.330,0.28,31.6,0.053,35.0,176.0,1.01030,3.15,0.38,8.8,6,white
3252,7.9,0.330,0.28,31.6,0.053,35.0,176.0,1.01030,3.15,0.38,8.8,6,white
1435,10.2,0.540,0.37,15.4,0.214,55.0,95.0,1.00369,3.18,0.77,9.0,6,red
1434,10.2,0.540,0.37,15.4,0.214,55.0,95.0,1.00369,3.18,0.77,9.0,6,red

In [ ]:
# Q 8C

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
1435,10.2,0.540,0.37,15.4,0.214,55.0,95.0,1.00369,3.18,0.77,9.0,6,red
1434,10.2,0.540,0.37,15.4,0.214,55.0,95.0,1.00369,3.18,0.77,9.0,6,red
3252,7.9,0.330,0.28,31.6,0.053,35.0,176.0,1.01030,3.15,0.38,8.8,6,white
3262,7.9,0.330,0.28,31.6,0.053,35.0,176.0,1.01030,3.15,0.38,8.8,6,white
4380,7.8,0.965,0.60,65.8,0.074,8.0,160.0,1.03898,3.39,0.69,11.7,6,white

In [ ]:
# Q 8D

4380    11.7
3262     8.8
3252     8.8
1435     9.0
1434     9.0
Name: alcohol, dtype: float64

In [41]:
fruits = ['apple', 'orange', 'apple']
# output: {'apple':2, 'orange':1}

output = {}
for fruit in fruits:
    if fruit not in output:
        output[fruit] = 1
    else:
        output[fruit] += 1

In [42]:
output

{'apple': 2, 'orange': 1}